/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC7;

public class Library {
    public static void main(String[] args) {
        System.out.println("Ali Code Chalenge 7");
    }
}
