/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Graph;

public class App {
    public static void main(String[] args) {
        GraphImplementation<String> test = new GraphImplementation<>();
        Node<String> node1 = new Node<>("ALI");
        System.out.println(node1.getValue());
        Node<String> node2 = new Node<>("FAWZI");
        System.out.println(test.addNode("AKEF").getValue());
    }
}
