/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list.zip;

public class Library {
    public static void main(String[] args) {
        System.out.println("Ali Akef Code Challenge 8");
        LinkedList list1 = new LinkedList();
        list1.insert(9);
        list1.insert(7);
        list1.insert(5);
        list1.insert(3);
        list1.insert(1);
        LinkedList list2 = new LinkedList();
//        list2.insert(10);
        list2.insert(8);
        list2.insert(6);
        list2.insert(4);
        list2.insert(2);
        System.out.println(list1.toString());
        System.out.println(list2.toString());
        System.out.println(LinkedList.linkedListZip(list1,list2).toString());
    }
}
