/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC10;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testStack() {
        Stack<String> list = new Stack<>();
        list.pushStack("1");
        list.pushStack("2");
        list.pushStack("3");
        list.pushStack("4");
        list.pushStack("5");
        list.pushStack("6");
        assertEquals("6" , list.peek());
        list.pushStack("50");
        list.pushStack("680");
        assertEquals("680" , list.peek());
    }
    @Test public  void testQueue(){
        Queue<Integer> queue = new Queue<>();
        queue.enQueue(11);
        queue.enQueue(13);
        queue.enQueue(14);
        queue.enQueue(15);
        queue.enQueue(19);
        queue.enQueue(22);
        queue.enQueue(29);
        queue.enQueue(82);
        assertEquals("{ 11 } -> { 13 } -> { 14 } -> { 15 } -> { 19 } -> { 22 } -> { 29 } -> { 82 } -> Null" , queue.toString());
        queue.deQueue();
        assertEquals("{ 13 } -> { 14 } -> { 15 } -> { 19 } -> { 22 } -> { 29 } -> { 82 } -> Null" , queue.toString());
    }
}
