/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QuickSort;

import java.util.Arrays;

public class App {

    public static void main(String[] args) {
        int[] arr = {8,4,23,42,16,15};
        System.out.println(Arrays.toString(QuickSort(arr,0,arr.length-1)));
    }

    //quickSort
    public static int[] QuickSort(int[] arr, int left, int right) {
        if (left < right) {
            int position = Partition(arr, left, right);
            QuickSort(arr, left, position - 1);
            QuickSort(arr, position + 1, right);
        }
        return arr;
    }

    //Partition
    public static int Partition(int[] arr, int left, int right) {
        int pivot = arr[right];
        int i = left - 1;
        for (int val = left; val < right; val++) {
            if (arr[val] < pivot) {
                i++;
                swapElement(arr, i, val);
            }
        }
        swapElement(arr, i + 1, right);
        return (i + 1);
    }

    //Swapped
    public static void swapElement(int[] arr, int i, int val) {
        int temp = arr[i];
        arr[i] = arr[val];
        arr[val] = temp;
    }
}
