/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QuickSort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        int[] arr = {8,4,23,42,16,15};
        int[] arr2 = {5,4,3,2,1};
        assertEquals( "[4, 8, 15, 16, 23, 42]" , Arrays.toString(classUnderTest.QuickSort(arr,0,arr.length-1)));
        assertEquals( "[1, 2, 3, 4, 5]" , Arrays.toString(classUnderTest.QuickSort(arr2,0,arr2.length-1)));
    }
}
