/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC9;

import sun.awt.image.ImageWatched;

import java.util.Arrays;

public class Library {
    public static void main(String[] args) {
        System.out.println("Question One");
        LinkedList list1 = new LinkedList();
        list1.insert(5);
        list1.insert(4);
        list1.insert(3);
        list1.insert(2);
        list1.insert(1);
        list1.Reversed(list1);

    }
}
