/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC10;

import java.util.Arrays;
import java.util.LinkedList;

public class App {
    public static void main(String[] args) {
        System.out.println("================================================STACK================================================");
        Stack<Integer> stack = new Stack<>();
        System.out.println("If the stack is empty return false else return true : " + stack.isEmpty());
        stack.pushStack(1);
        stack.pushStack(2);
        stack.pushStack(3);
        stack.pushStack(4);
        stack.pushStack(5);
        stack.pushStack(6);
        System.out.println("Max Size of Stack is " + stack.getMaxSize());
        System.out.println("Last value in the Stack is : " + stack.peek());
        stack.pushStack(7);
        stack.pushStack(10);
        System.out.println("Max Size of Stack after push tow value is " + stack.getMaxSize());
        System.out.println("Last value in the Stack after edited is : " + stack.peek());
        System.out.println(stack.toString());
        stack.popStack();
        System.out.println(stack.toString());
        System.out.println("Peek after edited value : " + stack.peek());
        System.out.println("If the stack is empty return false else return true : " + stack.isEmpty());
        System.out.println("================================================QUEUE================================================");
        Queue<Integer> queue = new Queue<>();
        System.out.println("If Empty return false else return True : " + queue.isEmpty());
        queue.enQueue(11);
        queue.enQueue(13);
        queue.enQueue(14);
        queue.enQueue(15);
        queue.enQueue(19);
        queue.enQueue(22);
        queue.enQueue(29);
        queue.enQueue(82);
        System.out.println("The Size of Queue : " + queue.getMaxSize());
        System.out.println("If Empty return false else return True : " + queue.isEmpty());
        System.out.println("Peek Value before Dequeue is : " + queue.peekQueue());
        System.out.println("The Value is deQueue is : " + queue.deQueue());
        System.out.println("Peek Value after Dequeue is : " + queue.peekQueue());
        System.out.println("The Size of Queue : " + queue.getMaxSize());
        System.out.println(queue.toString());
    }
}
