/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InsertionSort;

import java.util.ArrayList;
import java.util.Arrays;

public class Library {
    public static void main(String[] args) {
        System.out.println("Insertion Sort Code Challenge -> Ali Akef");
        System.out.println("-----------------------------------------");
        int[] arr = {8,4,23,42,16,15,-24,13,0,-9,42};
        System.out.println(Arrays.toString(InsertionSort(arr)));
    }

    //Swapped between index and minValueIndex
    public static int[] InsertionSort(int[] arr){
//        for (int i = 0 ; i < arr.length-1 ; i++){
//            int minIndex = i;
//            for (int j = i+1 ; j < arr.length ; j++){
//                if (arr[j] < arr[minIndex]){
//                    minIndex = j;
//                }
//            }
//            int temp = arr[minIndex];
//            arr[minIndex] = arr[i];
//            arr[i] = temp;
//        }
//        return arr;

        /* InsertionSort(int[] arr)

    FOR i = 1 to arr.length

      int j <-- i - 1
      int temp <-- arr[i]

      WHILE j >= 0 AND temp < arr[j]
        arr[j + 1] <-- arr[j]
        j <-- j - 1

      arr[j + 1] <-- temp*/
        for (int i = 1 ; i < arr.length ; i++){
            int j = i-1;
            int temp = arr[i];
            while(j >= 0 && temp < arr[j]){
                arr[j+1] = arr[j];
                j--;
            }
            arr[j+1] = temp;
        }
        return arr;
    }
}
