/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashTable;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App app = new App();
        HashTable age = new HashTable(7);
        age.Add(1,23);
        age.Add(8,18);
        age.Add(14,20);
        age.Add(13,31);
        age.Add(85,16);
        age.Add(4,10);
        assertEquals(23 , age.Get(1));
        assertEquals(6 , age.Hash(90));
        assertEquals(7 , age.arrSize);
        assertEquals(true , age.Contains(13));
    }
}
