/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;


public class Library {

    public static void main(String[] args) {
        System.out.println("Ali Akef CC6");
        System.out.println("------------------------------------------------------------------------");
        LinkedList list = new LinkedList();
        list.insert(5);
        list.insert(4);
        list.insert(3);
        list.insert(2);
        list.insert(1);
        list.append(6);
        list.insertAfter(4,100);
        list.insertBefore(3,15);
        System.out.println(list.isInclude(5));
        System.out.println(list.converToString());
    }
}
