/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Graph;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        GraphImplementation<String> test = new GraphImplementation<>();
        Node<String> node = new Node<>("ALI");
        Node<String> node2 = new Node<>("AKEF");
        assertEquals("ALI" , node.getValue());

        GraphImplementation<String> nnull = new GraphImplementation<>();
        assertNull(nnull.getNodes());

        test.addEdge("Ali" , "Akef");
    }
}
